=== forpdi/plataformafor-back/src/main/resources/forpdi_structure_1.0.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	version="1.0">
	<xs:simpleType name="DataTypes">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Currency" />
			<xs:enumeration value="DateField" />
			<xs:enumeration value="DateTimeField" />
			<xs:enumeration value="NumberField" />
			<xs:enumeration value="Percentage" />
			<xs:enumeration value="TextArea" />
			<xs:enumeration value="TextField" />
			<xs:enumeration value="BudgetField" />
			<xs:enumeration value="ActionPlanField" />
			<xs:enumeration value="ScheduleField" />
			<xs:enumeration value="SelectField" />
			<xs:enumeration value="TableField" />
			<xs:enumeration value="ResponsibleField" />
			<xs:enumeration value="AttachmentField" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ScheduleValueTypes">
		<xs:restriction base="xs:string">
			<xs:enumeration value="TextField" />
			<xs:enumeration value="NumberField" />
			<xs:enumeration value="DateField" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ScheduleValue">
		<xs:sequence>
			<xs:element name="valueLabel" type="xs:string" />
			<xs:element name="valueType" type="ScheduleValueTypes" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OptionLabel">
		<xs:sequence>
			<xs:element name="label" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Attribute">
		<xs:all>
			<xs:element name="label" type="xs:string" />
			<xs:element name="description" type="xs:string" />
			<xs:element name="type" type="DataTypes" />
			<xs:element name="optionsField">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="optionLabel" minOccurs="0" maxOccurs="unbounded"
							type="OptionLabel" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="scheduleOptions">
				<xs:complexType>
					<xs:all>
						<xs:element name="periodicity" type="xs:boolean"
							default="true" />
						<xs:element name="scheduleValues">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="scheduleValue" minOccurs="0"
										maxOccurs="unbounded" type="ScheduleValue" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:all>
				</xs:complexType>
			</xs:element>
		</xs:all>
		<xs:attribute name="required" type="xs:boolean" default="false" />
		<xs:attribute name="visibleInTables" type="xs:boolean" default="false" />
		<xs:attribute name="finishDate" type="xs:boolean" default="false" />
		<xs:attribute name="expectedField" type="xs:boolean" default="false" />
		<xs:attribute name="justificationField" type="xs:boolean" default="false" />
		<xs:attribute name="minimumField" type="xs:boolean" default="false" />
		<xs:attribute name="maximumField" type="xs:boolean" default="false" />
		<xs:attribute name="reachedField" type="xs:boolean" default="false" />
		<xs:attribute name="referenceField" type="xs:boolean" default="false" />
		<xs:attribute name="polarityField" type="xs:boolean" default="false" />
		<xs:attribute name="formatField" type="xs:boolean" default="false" />
		<xs:attribute name="periodicityField" type="xs:boolean" default="false" />
		<xs:attribute name="beginField" type="xs:boolean" default="false" />
		<xs:attribute name="endField" type="xs:boolean" default="false" />
		<xs:attribute name="bscField" type="xs:boolean" default="false" />
	</xs:complexType>

	<xs:element name="level" type="StructureLevel" />

	<xs:complexType name="StructureLevel">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="description" type="xs:string" />
			<xs:element name="indicator" type="xs:boolean" default="false" />
			<xs:element name="goal" type="xs:boolean" default="false" />
			<xs:element name="objective" type="xs:boolean" default="false" />
			<xs:element name="attributes">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="attribute" minOccurs="1" maxOccurs="unbounded"
							type="Attribute" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="level" minOccurs="0" maxOccurs="1"
				type="StructureLevel" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="structure">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="structureName" type="xs:string" />
				<xs:element name="structureDescription" type="xs:string" />
				<xs:element name="structureLevels">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="level" minOccurs="1" maxOccurs="unbounded"
								type="StructureLevel" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== forpdi/plataformafor-back/src/main/resources/structure-example.xml
<?xml version="1.0" encoding="UTF-8" ?>
<structure xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="forpdi_structure_1.0.xsd">
	<structureName>Plano de Exemplo</structureName>
	<structureDescription>
		Estrutura de exemplo de um PDI de uma Universidade.
	</structureDescription>
	<structureLevels>
		<level>
			<name>Area</name>
			<description>Nível raiz, define as áreas da universidade.</description>
			<indicator>false</indicator>
			<goal>false</goal>
			<objective>false</objective>
			<attributes>
				<attribute required="true">
					<type>TextField</type>
					<label>Nome</label>
					<description>Nome da Área</description>
					<optionsField></optionsField>
					<scheduleOptions>
						<periodicity></periodicity>
						<scheduleValues></scheduleValues>
					</scheduleOptions>
				</attribute>
				<attribute required="true">
					<type>TextArea</type>
					<label>Descrição</label>
					<description>Descrição da Área</description>
					<optionsField></optionsField>
					<scheduleOptions>
						<periodicity></periodicity>
						<scheduleValues></scheduleValues>
					</scheduleOptions>
				</attribute>
			</attributes>
		</level>
		<level>
			<name>Objetivo</name>
			<description></description>
			<indicator>false</indicator>
			<goal>false</goal>
			<objective>true</objective>
			<attributes>
				<attribute required="true">
					<type>TextField</type>
					<label>Nome</label>
					<description>Nome do Objetivo</description>
					<optionsField></optionsField>
					<scheduleOptions>
						<periodicity></periodicity>
						<scheduleValues></scheduleValues>
					</scheduleOptions>
				</attribute>
				<attribute required="true">
					<type>TextArea</type>
					<label>Descrição</label>
					<description>Descrição do Objetivo</description>
					<optionsField></optionsField>
					<scheduleOptions>
						<periodicity></periodicity>
						<scheduleValues></scheduleValues>
					</scheduleOptions>
				</attribute>
			</attributes>
		</level>
		<level>
			<name>Indicador</name>
			<description></description>
			<indicator>true</indicator>
			<goal>false</goal>
			<objective>false</objective>
			<attributes>
				<attribute required="true">
					<type>TextField</type>
					<label>Nome</label>
					<description>Nome do Indicador</description>
					<optionsField></optionsField>
					<scheduleOptions>
						<periodicity></periodicity>
						<scheduleValues></scheduleValues>
					</scheduleOptions>
				</attribute>
				<attribute required="true">
					<type>TextArea</type>
					<label>Descrição</label>
					<description>Descrição do Indicador</description>
					<optionsField></optionsField>
					<scheduleOptions>
						<periodicity></periodicity>
						<scheduleValues></scheduleValues>
					</scheduleOptions>
				</attribute>
			</attributes>
		</level>
		<level>
			<name>Meta</name>
			<description></description>
			<indicator>false</indicator>
			<goal>true</goal>
			<objective>false</objective>
			<attributes>
				<attribute required="true">
					<type>TextField</type>
					<label>Nome</label>
					<description>Nome da Meta</description>
					<optionsField></optionsField>
					<scheduleOptions>
						<periodicity></periodicity>
						<scheduleValues></scheduleValues>
					</scheduleOptions>
				</attribute>
				<attribute required="true">
					<type>TextArea</type>
					<label>Descrição</label>
					<description>Descrição da Meta</description>
					<optionsField></optionsField>
					<scheduleOptions>
						<periodicity></periodicity>
						<scheduleValues></scheduleValues>
					</scheduleOptions>
				</attribute>
			</attributes>
		</level>
	</structureLevels>
</structure>
